<?php
$z[0]=Array("item","",4,82);
$z[0][4]['name']="插件管理器";
$z[0][4]['link']="plus_main.php";
$z[0][4]['rank']="10";
$z[0][4]['target']="main";
$z[1]=Array("item","",86,182);
$z[1][4]['name']="友情链接";
$z[1][4]['link']="friendlink_main.php";
$z[1][4]['rank']="plus_友情链接";
$z[1][4]['target']="main";
$z[2]=Array("item","",184,252);
$z[2][4]['name']="XML地图";
$z[2][4]['link']="map.php";
$z[2][4]['rank']="plus_starget=";
$z[2][4]['main']="";

?>