<li>
        <div class="al_img"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" width="235" height="174" /></a></div>
        <div class="al_t"><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></div>
        <div class="al_sx"><span class="c_8e8e8e">印刷类别：[field:typename/]　</span> <span class="c_8e8e8e ml_10">点击：(<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=1" type='text/javascript' language="javascript"></script>)</span></div>
      </li>