<?php
$z[0]=Array("field","",185,204);
$z[0][4]['name']="title";
$z[1]=Array("global","",205,231);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",272,294);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",334,385);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1563,1598);
$z[4][4]['filename']="head.htm";
$z[5]=Array("geturl","    \r\n@me = GetCurUrl();    \r\n",1825,1899);
$z[5][4]['runphp']="’yes’";
$z[6]=Array("field","",1903,1932);
$z[6][4]['name']="position";
$z[7]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">更多>></a></span><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",2092,2275);
$z[7][4]['typeid']="40";
$z[8]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a></li>\r\n          ",2353,2543);
$z[8][4]['type']="son";
$z[8][4]['noself']="yes";
$z[8][4]['typeid']="40";
$z[9]=Array("include","",2612,2650);
$z[9][4]['filename']="contact.htm";
$z[10]=Array("field","",2778,2798);
$z[10][4]['name']="litpic";
$z[11]=Array("field","",2941,2959);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",3274,3362);
$z[12][4]['function']="str_replace(' 上一篇：','<'.'br'.' />下一篇：',@me)";
$z[13]=Array("include","",3403,3440);
$z[13][4]['filename']="footer.htm";

?>