<li>
                  
              <!--pic -->
              <div class="tab-news-text">

                      <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
                <p>分类：[field:typename/] 日期：[field:pubdate function="MyDate('Y-m-d',@me)"/] 浏览次数：<script src="/plus/count.php?view=yes&aid=[field:id/]&mid=1" type='text/javascript' language="javascript"></script>  </p>
                      <p>&nbsp;&nbsp;&nbsp; [field:description/]...</p>
                      <p class="c-f47e29 ta_r"><a href="[field:arcurl/]">查看详情>></a></p>
              </div><!--text -->
                  <div style="clear: both;"></div>
               </li>