<?php
$z[0]=Array("field","",185,204);
$z[0][4]['name']="title";
$z[1]=Array("global","",205,231);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",272,294);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",334,385);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",610,645);
$z[4][4]['filename']="head.htm";
$z[5]=Array("geturl","    \r\n@me = GetCurUrl();    \r\n",910,984);
$z[5][4]['runphp']="’yes’";
$z[6]=Array("field","",988,1017);
$z[6][4]['name']="position";
$z[7]=Array("type","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">更多>></a></span><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",1221,1404);
$z[7][4]['typeid']="40";
$z[8]=Array("channel","\r\n                    <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\" target=\"_blank\">[field:typename/]</a></li>\r\n ",1462,1653);
$z[8][4]['type']="son";
$z[8][4]['noself']="yes";
$z[8][4]['typeid']="40";
$z[9]=Array("include","",1700,1738);
$z[9][4]['filename']="contact.htm";
$z[10]=Array("list","\r\n\r\n\r\n                 <li>\r\n\r\n\r\n                    <div class=\"pro-list-pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"174\" height=\"134\" border=\"0\" /></a></div>\r\n\r\n\r\n                    <!--pic -->\r\n\r\n\r\n                    <div class=\"pro-list-text\"><a href=\"[field:arcurl/]\">[field:title/]</a></div><!--text -->\r\n\r\n\r\n                 </li>\r\n",1890,2310);
$z[10][4]['pagesize']="16";
$z[11]=Array("pagelist","",2433,2511);
$z[11][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2663,2700);
$z[12][4]['filename']="footer.htm";

?>